filter:
  excluded_paths: [tests/*]

checks:
  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true
    code_rating: true
    duplication: true

build:
  nodes:
    php72:
      environment:
        php:
          version: 7.2
      services:
        mariadb: 10.3
      tests:
        override:
          - php-scrutinizer-run
          -
            command: mysql -e 'CREATE DATABASE db_rebuild;' && vendor/bin/phpunit --coverage-clover=coverage72
            coverage:
              file: coverage72
              format: php-clover
